#!/usr/bin/env bash
# Run the end-to-end suite exactly as CI does: Linux, x86_64, no GPU.
#
# This exists because a green local run stopped meaning anything. The macOS
# developer machine has a real GPU and a different libc, fontconfig and
# freetype; `ubuntu-latest` has none of those. A suite that passes here and
# fails there is not flaky, it is untested — and that is precisely how a
# local `pnpm goal:check` reported 33 of 33 green while the public checks
# were red.
#
# UV_USE_IO_URING=0 is required when the host emulates x86_64: libuv's
# io_uring backend trips an assertion under QEMU
# ("uv__io_poll: Assertion `errno == EEXIST' failed"). It changes only how
# Node polls for I/O, not what the tests do.
#
# The image is the same Playwright release the repository pins. It runs on
# the host's native architecture.
#
# What this container is NOT for: screenshot baselines. CI is linux/amd64,
# and forcing that platform on an Apple Silicon host makes Chromium
# segfault under QEMU ("Received signal 11 SEGV_MAPERR") — a browser is too
# much for user-mode emulation. Baselines are therefore generated by the
# `linux-baselines` workflow on a real ubuntu-latest runner, downloaded,
# inspected, and committed. Guessing them here and hoping would be exactly
# the kind of unverified claim this repository is supposed to refuse.
#
# What it IS for: catching everything else Linux does differently —
# missing system libraries, font availability, case-sensitive paths,
# locale, and any test that quietly depends on macOS behaviour.
#
#   tools/ci-parity/run-linux.sh                  # full suite
#   tools/ci-parity/run-linux.sh --update-snapshots
#   tools/ci-parity/run-linux.sh --project=city
#
# Any arguments are passed through to `playwright test`.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PLAYWRIGHT_VERSION="$(node -p "require('${REPO_ROOT}/node_modules/@playwright/test/package.json').version")"
IMAGE="mcr.microsoft.com/playwright:v${PLAYWRIGHT_VERSION}-noble"

if ! docker info >/dev/null 2>&1; then
  echo "Docker is not running. Start Docker Desktop or 'colima start'." >&2
  exit 1
fi

echo "CI parity: ${IMAGE} on linux/amd64"
echo "Repository: ${REPO_ROOT}"

# node_modules and the Playwright browser cache are container-local: the
# host's macOS binaries cannot run on Linux. Everything else is bind-mounted
# so results, baselines and reports land back in the working tree.
docker run --rm -t \
  -v "${REPO_ROOT}:/work" \
  -v qsimcity-ci-parity-node-modules:/work/node_modules \
  -w /work \
  -e CI=1 \
  -e PLAYWRIGHT_BROWSERS_PATH=/ms-playwright \
  -e UV_USE_IO_URING=0 \
  -e PNPM_HOME=/pnpm \
  -v qsimcity-ci-parity-pnpm-store:/pnpm \
  "${IMAGE}" \
  bash -lc '
    set -euo pipefail
    corepack enable
    # Keep the store out of the bind-mounted working tree; it defaulted
    # there once and swept 28k files into a commit.
    pnpm config set store-dir /pnpm/store --global
    pnpm install --frozen-lockfile
    pnpm build
    echo "--- renderer the container actually gets ---"
    node -e "console.log(process.platform, process.arch)"
    pnpm exec playwright test '"$*"'
  '
