import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { applyBlocks } from './blocks.js';
import { readFacts } from './facts.js';

/**
 * Writes measured values into the documentation's generated regions.
 *
 * The counterpart to `pnpm docs:check`. Both read the same facts, so a
 * document is either in sync or the check fails; there is no third state in
 * which a number is merely "probably still right".
 *
 * `release-evidence/summary.md` is regenerated in full rather than patched,
 * because it is a report about a release rather than prose about the
 * project — the previous hand-written one still described version 1.0.0 and
 * five evidence artifacts when there were fourteen.
 */

const ROOT = new URL('../..', import.meta.url).pathname;

const TARGETS = ['README.md', 'docs/WISER_SUBMISSION.md'];

const facts = readFacts();
let changed = 0;

for (const target of TARGETS) {
  const path = join(ROOT, target);
  if (!existsSync(path)) continue;
  const before = readFileSync(path, 'utf8');
  const after = applyBlocks(before, facts);
  if (after !== before) {
    writeFileSync(path, after);
    changed += 1;
    console.log(`  updated ${target}`);
  }
}

// ------------------------------------------------------------- summary.md

const evidenceFiles: readonly { readonly path: string; readonly what: string }[] = [
  { path: 'coverage/per-package-coverage.json', what: 'Per-package line and branch coverage' },
  {
    path: 'mutation/mutation-report.json',
    what: 'Generative mutation testing of scientific invariants',
  },
  { path: 'python/python-verify.json', what: 'Qiskit bridge: pytest, pyright, ruff' },
  {
    path: 'trace-reproducibility/reproducibility.json',
    what: 'Cross-process and cross-language trace hashing',
  },
  { path: 'security/security-report.json', what: 'Dependency audit and policy scans' },
  { path: 'performance.json', what: 'Chunk-level byte budgets from the real build' },
  {
    path: 'lighthouse/lighthouse-report.json',
    what: 'Lighthouse across four targets, three runs each',
  },
  { path: 'visual-benchmark/benchmark.json', what: 'Visual quality rubric scoring' },
  { path: 'wiser-fps/fps-report.json', what: 'Frame-time percentiles, capped and uncapped' },
  { path: 'wiser-screenshots/manifest.json', what: 'The fifteen WISER surface captures' },
  { path: 'wiser-reviews/reviews.json', what: 'Separated adversarial review verdicts' },
  { path: 'remount/remount-report.json', what: 'Fixed-count 3D/2D remount safety' },
  { path: 'soak/soak-report.json', what: 'Ten-minute production soak' },
  { path: 'fresh-clone/fresh-clone.json', what: 'Verification inside a clean clone' },
  { path: 'demo/demo-manifest.json', what: 'Demo recording, bound to the source tree' },
  { path: 'goal-check.txt', what: 'Full output of pnpm goal:check' },
];

const minutes = Math.floor(facts.demoSeconds / 60);
const seconds = String(facts.demoSeconds % 60).padStart(2, '0');

const summary = [
  `# Release evidence — QSimCity ${facts.productVersion}`,
  '',
  '<!-- Generated by `pnpm docs:sync`. Do not edit by hand: the previous',
  '     hand-written summary still described version 1.0.0 and five',
  '     artifacts long after there were sixteen. -->',
  '',
  `Every measurement below was produced from source tree \`${facts.sourceTreeHash}\``,
  'by a command that exited zero, and recorded in an envelope that binds it to',
  'that tree. `pnpm goal:check` recomputes the verdicts and rejects any envelope',
  'whose tree hash no longer matches, so evidence cannot outlive the code it',
  'measured.',
  '',
  '## Results',
  '',
  '| What | Measured |',
  '| --- | --- |',
  `| Definition-of-Done gate | ${facts.goalChecksPassed} passed, ${facts.goalChecksFailed} failed |`,
  `| Unit and integration tests | ${facts.unitTests} |`,
  `| End-to-end tests | ${facts.e2eTests} |`,
  `| Qiskit agreement | ${facts.pytestPassed} pytest against Qiskit ${facts.qiskitVersion} / Aer ${facts.aerVersion} |`,
  `| Coverage | ${facts.coverageLines}% lines, ${facts.coverageBranches}% branches |`,
  `| Mutation score | ${facts.mutationScore} (${facts.mutantsKilled}/${facts.mutantsGenerated} killed, ${facts.mutantsSurvived} equivalent) |`,
  `| Trace reproducibility | ${facts.reproProcesses} processes, ${facts.reproDistinctSemanticHashes} distinct semanticHash |`,
  `| Ten-minute soak | ${facts.soakSeconds}s, ${facts.soakCycles} cycles, ${facts.soakConsoleErrors} console errors |`,
  `| 3D/2D remount | ${facts.remountCycles} cycles, ${facts.remountPeakContexts} WebGL contexts left behind |`,
  `| Initial JS | ${facts.initialJsKib} KiB gzip (${facts.totalJsKib} KiB total) |`,
  `| Clean clone | ${facts.freshCloneSteps} steps, ${facts.freshCloneFailed} failed |`,
  `| Demo recording | ${minutes} min ${seconds} s, ${facts.demoCaptions} captions |`,
  '',
  '## Deployment',
  '',
  'Production serves `main` at <https://qsimcity.vercel.app>. The deployment is',
  'bound to the merge commit through the GitHub deployments API, and the served',
  'bundle is the one built from this tree.',
  '',
  '## Artifacts in this directory',
  '',
  '| File | Contents |',
  '| --- | --- |',
  ...evidenceFiles.map(({ path, what }) => `| \`${path}\` | ${what} |`),
  '',
  '## What is not measured here',
  '',
  '- No human learning outcome. The assessment instrument and protocol are',
  '  published and unrun; the instrument itself needs revision first.',
  '- The adversarial reviews were performed by AI agents, not human experts.',
  '- Mobile frame times are Chromium emulation on a desktop GPU.',
  '',
].join('\n');

const summaryPath = join(ROOT, 'release-evidence', 'summary.md');
const previousSummary = existsSync(summaryPath) ? readFileSync(summaryPath, 'utf8') : '';
if (previousSummary !== summary) {
  writeFileSync(summaryPath, summary);
  changed += 1;
  console.log('  updated release-evidence/summary.md');
}

console.log(
  changed === 0 ? 'docs:sync: already in sync.' : `docs:sync: updated ${changed} file(s).`,
);
