import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { parseTraceJson, traceContentHash } from '../src/index.js';

/**
 * Schema-parity gate: every trace generated by the Python Qiskit bridge must
 * validate against the TypeScript schema and reproduce the committed
 * content hashes in examples/traces/manifest.json.
 */

const ROOT = new URL('../../..', import.meta.url).pathname;
const TRACES_DIR = join(ROOT, 'examples', 'traces');

function traceFiles(): string[] {
  return readdirSync(TRACES_DIR).filter((f) => f.endsWith('.qsimcity.json'));
}

describe('Qiskit bridge trace parity', () => {
  it('sample traces exist', () => {
    expect(traceFiles().length).toBeGreaterThanOrEqual(5);
  });

  it('every committed sample trace passes TypeScript validation', () => {
    for (const file of traceFiles()) {
      const json = readFileSync(join(TRACES_DIR, file), 'utf8');
      const trace = parseTraceJson(json);
      expect(trace.generator.generator, file).toBe('qsimcity-qiskit-bridge');
      expect(trace.events.length, file).toBeGreaterThan(0);
      expect(trace.compiledCircuit, file).not.toBeNull();
      expect(trace.initialLayout, file).not.toBeNull();
    }
  });

  it('trace content hashes match the committed manifest (Python/TS hash parity)', () => {
    const manifest = JSON.parse(readFileSync(join(TRACES_DIR, 'manifest.json'), 'utf8')) as Record<
      string,
      string
    >;
    for (const [id, expectedHash] of Object.entries(manifest)) {
      const json = readFileSync(join(TRACES_DIR, `${id}.qsimcity.json`), 'utf8');
      const trace = parseTraceJson(json);
      expect(traceContentHash(trace), id).toBe(expectedHash);
    }
  });

  it('qiskit traces carry qiskit_transpiler provenance with package versions', () => {
    for (const file of traceFiles()) {
      const trace = parseTraceJson(readFileSync(join(TRACES_DIR, file), 'utf8'));
      const transpilerEvents = trace.events.filter((e) => e.source === 'qiskit_transpiler');
      expect(transpilerEvents.length, file).toBeGreaterThan(0);
      expect(trace.packageVersions['qiskit'], file).toBeDefined();
      expect(trace.packageVersions['qiskit-aer'], file).toBeDefined();
      for (const e of transpilerEvents) expect(e.certainty).toBe('COMPUTED');
    }
  });

  it('compiled circuits respect the declared basis gates', () => {
    for (const file of traceFiles()) {
      const trace = parseTraceJson(readFileSync(join(TRACES_DIR, file), 'utf8'));
      for (const instr of trace.compiledCircuit!.instructions) {
        if (instr.kind === 'gate') {
          expect(['rz', 'sx', 'x', 'cx'], `${file}: ${instr.name}`).toContain(instr.name);
        }
      }
    }
  });
});
