import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { parseTraceJson, semanticHash, artifactHash } from '../src/index.js';

/**
 * Schema-parity gate: every trace generated by the Python Qiskit bridge must
 * validate against the TypeScript schema and reproduce the committed
 * content hashes in examples/traces/manifest.json.
 */

const ROOT = new URL('../../..', import.meta.url).pathname;
const TRACES_DIR = join(ROOT, 'examples', 'traces');

function traceFiles(): string[] {
  return readdirSync(TRACES_DIR).filter((f) => f.endsWith('.qsimcity.json'));
}

describe('Qiskit bridge trace parity', () => {
  it('sample traces exist', () => {
    expect(traceFiles().length).toBeGreaterThanOrEqual(5);
  });

  it('every committed sample trace passes TypeScript validation', () => {
    for (const file of traceFiles()) {
      const json = readFileSync(join(TRACES_DIR, file), 'utf8');
      const trace = parseTraceJson(json);
      expect(trace.generator.generator, file).toBe('qsimcity-qiskit-bridge');
      expect(trace.events.length, file).toBeGreaterThan(0);
      expect(trace.compiledCircuit, file).not.toBeNull();
      expect(trace.initialLayout, file).not.toBeNull();
    }
  });

  it('semantic hashes computed in TypeScript match the Python-written manifest', () => {
    const manifest = JSON.parse(readFileSync(join(TRACES_DIR, 'manifest.json'), 'utf8')) as Record<
      string,
      { semanticHash: string; artifactHash: string }
    >;
    for (const [id, hashes] of Object.entries(manifest)) {
      const json = readFileSync(join(TRACES_DIR, `${id}.qsimcity.json`), 'utf8');
      const trace = parseTraceJson(json);
      expect(semanticHash(trace), `${id} semanticHash`).toBe(hashes.semanticHash);
    }
  });

  it('artifact hashes match the committed bytes exactly', () => {
    const manifest = JSON.parse(readFileSync(join(TRACES_DIR, 'manifest.json'), 'utf8')) as Record<
      string,
      { semanticHash: string; artifactHash: string }
    >;
    for (const [id, hashes] of Object.entries(manifest)) {
      const json = readFileSync(join(TRACES_DIR, `${id}.qsimcity.json`), 'utf8');
      expect(artifactHash(json), `${id} artifactHash`).toBe(hashes.artifactHash);
    }
  });

  it('committed traces carry real Qiskit pass telemetry, excluded from semantics', () => {
    for (const file of traceFiles()) {
      const json = readFileSync(join(TRACES_DIR, file), 'utf8');
      const trace = parseTraceJson(json);
      expect(trace.telemetry?.executedPasses?.length, file).toBeGreaterThan(5);
      expect(trace.telemetry!.executedPasses).toContain('BasisTranslator');
      // Rewriting telemetry must not move the semantic hash.
      const before = semanticHash(trace);
      const mutated = {
        ...trace,
        telemetry: { executedPasses: ['Different'], executedPassCount: 1 },
      };
      expect(semanticHash(mutated)).toBe(before);
    }
  });

  it('qiskit traces carry qiskit_transpiler provenance with package versions', () => {
    for (const file of traceFiles()) {
      const trace = parseTraceJson(readFileSync(join(TRACES_DIR, file), 'utf8'));
      const transpilerEvents = trace.events.filter((e) => e.source === 'qiskit_transpiler');
      expect(transpilerEvents.length, file).toBeGreaterThan(0);
      expect(trace.packageVersions['qiskit'], file).toBeDefined();
      expect(trace.packageVersions['qiskit-aer'], file).toBeDefined();
      for (const e of transpilerEvents) expect(e.certainty).toBe('COMPUTED');
    }
  });

  /**
   * The contract semanticHash exists to enforce, tested in both directions.
   *
   * This is the defect that made CI red while the local gate reported a
   * clean 33/33: `packageVersions` was inside the semantic view and carries
   * `platform.python_version()`, so the committed traces (generated on
   * Python 3.12.12) could not be reproduced on the CI runner (3.12.3) even
   * though every circuit, layout, metric, result and event was identical.
   */
  describe('semanticHash covers the science, not the environment', () => {
    const sample = (): ReturnType<typeof parseTraceJson> =>
      parseTraceJson(readFileSync(join(TRACES_DIR, traceFiles()[0]!), 'utf8'));

    it('is unmoved by environment and package versions', () => {
      const trace = sample();
      const before = semanticHash(trace);
      const mutated = {
        ...trace,
        packageVersions: {
          ...trace.packageVersions,
          python: '3.99.0',
          qiskit: '99.0.0',
          'qiskit-aer': '99.0.0',
        },
      };
      expect(semanticHash(mutated)).toBe(before);
    });

    it('is unmoved by identity and timestamp', () => {
      const trace = sample();
      const before = semanticHash(trace);
      expect(
        semanticHash({ ...trace, traceId: 't-different', createdAt: '2000-01-01T00:00:00.000Z' }),
      ).toBe(before);
    });

    it('but the artifact hash does move when versions change', () => {
      const file = traceFiles()[0]!;
      const json = readFileSync(join(TRACES_DIR, file), 'utf8');
      const before = artifactHash(json);
      const changed = json.replace(/"python": "[^"]+"/, '"python": "3.99.0"');
      expect(changed, 'the fixture must actually contain a python version').not.toBe(json);
      expect(artifactHash(changed)).not.toBe(before);
    });

    it('moves for every change that is actually scientific', () => {
      const trace = sample();
      const before = semanticHash(trace);
      const circuit = trace.inputCircuit;

      // Circuit.
      expect(
        semanticHash({
          ...trace,
          inputCircuit: { ...circuit, instructions: circuit.instructions.slice(0, -1) },
        }),
        'input circuit',
      ).not.toBe(before);
      // Compiled circuit.
      expect(
        semanticHash({
          ...trace,
          compiledCircuit: {
            ...trace.compiledCircuit!,
            instructions: trace.compiledCircuit!.instructions.slice(0, -1),
          },
        }),
        'compiled circuit',
      ).not.toBe(before);
      // Layouts.
      expect(
        semanticHash({ ...trace, initialLayout: [...trace.initialLayout!].reverse() }),
        'initial layout',
      ).not.toBe(before);
      expect(
        semanticHash({
          ...trace,
          finalLayout: [...(trace.finalLayout ?? [0])].reverse().concat(9),
        }),
        'final layout',
      ).not.toBe(before);
      // Metrics.
      expect(
        semanticHash({
          ...trace,
          metrics: trace.metrics.map((m, i) => (i === 0 ? { ...m, depth: m.depth + 9999 } : m)),
        }),
        'metrics',
      ).not.toBe(before);
      // Results.
      expect(
        semanticHash({
          ...trace,
          results: {
            ...trace.results,
            idealCounts: {
              ...trace.results.idealCounts!,
              counts: { ...trace.results.idealCounts!.counts, '11111': 7 },
            },
          },
        }),
        'results',
      ).not.toBe(before);
      // Events.
      expect(semanticHash({ ...trace, events: trace.events.slice(0, -1) }), 'events').not.toBe(
        before,
      );
      // Run configuration.
      expect(semanticHash({ ...trace, seed: 'other-seed' }), 'seed').not.toBe(before);
      expect(semanticHash({ ...trace, shots: trace.shots + 1 }), 'shots').not.toBe(before);
      expect(semanticHash({ ...trace, deviceId: 'other-device' }), 'deviceId').not.toBe(before);
    });
  });

  it('compiled circuits respect the declared basis gates', () => {
    for (const file of traceFiles()) {
      const trace = parseTraceJson(readFileSync(join(TRACES_DIR, file), 'utf8'));
      for (const instr of trace.compiledCircuit!.instructions) {
        if (instr.kind === 'gate') {
          expect(['rz', 'sx', 'x', 'cx'], `${file}: ${instr.name}`).toContain(instr.name);
        }
      }
    }
  });
});
