import { CITY_SCALE } from './districts.js';
import type { Vec2 } from './util.js';

/**
 * The arterial road network (spec §2.2): the west-east Processing Boulevard,
 * north and south collector roads, vertical avenues between districts, and
 * the two quay roads. Local streets inside districts are generated by
 * `blocks.ts` and merged by `city-plan.ts`; both use the same segment shape.
 *
 * Every segment is an axis-aligned straight in the x/z plane. Elevation is
 * not stored here — road surfaces sample `terrainHeight` along their length,
 * so roads follow the ground by construction.
 */

export type RoadClass = 'boulevard' | 'collector' | 'avenue' | 'local' | 'quay';

export interface RoadSegment {
  readonly id: string;
  readonly roadClass: RoadClass;
  readonly a: Vec2;
  readonly b: Vec2;
  /** Carriageway width in meters (both directions combined). */
  readonly width: number;
  /** Sidewalk width on each side, in meters. */
  readonly sidewalk: number;
  /** Median strip width for dual carriageways, 0 otherwise. */
  readonly median: number;
}

function seg(
  id: string,
  roadClass: RoadClass,
  a: readonly [number, number],
  b: readonly [number, number],
  width: number,
  sidewalk: number,
  median = 0,
): RoadSegment {
  // Endpoints are authored on the compact grid and scaled to city scale;
  // widths are true meters and stay unscaled.
  return {
    id,
    roadClass,
    a: { x: a[0] * CITY_SCALE, z: a[1] * CITY_SCALE },
    b: { x: b[0] * CITY_SCALE, z: b[1] * CITY_SCALE },
    width,
    sidewalk,
    median,
  };
}

/**
 * Hand-authored arterial plan. Vertical avenues run between district zones;
 * the boulevard and collectors cross the city. Positions are chosen so every
 * district touches at least one arterial (connectivity is tested).
 */
export const ARTERIAL_SEGMENTS: readonly RoadSegment[] = [
  // The Processing Boulevard: dual carriageway with a planted median. It
  // terminates at the QPU campus gate plaza — the fenced campus itself has
  // no public through-road.
  seg('blvd', 'boulevard', [-206, 20], [158, 20], 15, 3, 3),
  // Collectors reach the east quay so the harbor loop closes.
  seg('col-north', 'collector', [-135, -26], [232, -26], 10, 2),
  seg('col-south', 'collector', [-190, 95], [232, 95], 11, 2.5),
  // Vertical avenues (north-south).
  seg('ave-west', 'avenue', [-190, -26], [-190, 95], 9, 2),
  seg('ave-port', 'avenue', [-132, -26], [-132, 95], 9, 2),
  seg('ave-foundry', 'avenue', [-69, -26], [-69, 95], 9, 2),
  seg('ave-exchange', 'avenue', [-14, -26], [-14, 168], 9, 2),
  seg('ave-transit', 'avenue', [44, -26], [44, 95], 9, 2),
  seg('ave-works', 'avenue', [97, -26], [97, 95], 9, 2),
  seg('ave-tower', 'avenue', [150, -26], [150, 95], 9, 2),
  // Quay roads along the waterfronts.
  seg('quay-west', 'quay', [-200, -20], [-200, 60], 7, 2),
  seg('quay-east', 'quay', [232, -26], [232, 122], 7, 2),
];

/** Full corridor half-width including sidewalks (for block subtraction). */
export function corridorHalfWidth(segment: RoadSegment): number {
  return segment.width / 2 + segment.median / 2 + segment.sidewalk;
}

export interface RoadRect {
  readonly minX: number;
  readonly maxX: number;
  readonly minZ: number;
  readonly maxZ: number;
}

/** Axis-aligned footprint of a segment including sidewalks. */
export function corridorRect(segment: RoadSegment): RoadRect {
  const half = corridorHalfWidth(segment);
  return {
    minX: Math.min(segment.a.x, segment.b.x) - (segment.a.z === segment.b.z ? 0 : half),
    maxX: Math.max(segment.a.x, segment.b.x) + (segment.a.z === segment.b.z ? 0 : half),
    minZ: Math.min(segment.a.z, segment.b.z) - (segment.a.x === segment.b.x ? 0 : half),
    maxZ: Math.max(segment.a.z, segment.b.z) + (segment.a.x === segment.b.x ? 0 : half),
  };
}

export function isHorizontal(segment: RoadSegment): boolean {
  return segment.a.z === segment.b.z;
}

export interface Junction {
  readonly id: string;
  readonly position: Vec2;
  readonly segmentIds: readonly string[];
}

/** Point where two axis-aligned segments cross or touch, if any. */
function intersect(s1: RoadSegment, s2: RoadSegment): Vec2 | null {
  const h = isHorizontal(s1) ? s1 : isHorizontal(s2) ? s2 : null;
  const v = !isHorizontal(s1) ? s1 : !isHorizontal(s2) ? s2 : null;
  if (!h || !v || h === v) return null;
  const [hx1, hx2] = [Math.min(h.a.x, h.b.x), Math.max(h.a.x, h.b.x)];
  const [vz1, vz2] = [Math.min(v.a.z, v.b.z), Math.max(v.a.z, v.b.z)];
  const tolerance = 0.5;
  if (v.a.x < hx1 - tolerance || v.a.x > hx2 + tolerance) return null;
  if (h.a.z < vz1 - tolerance || h.a.z > vz2 + tolerance) return null;
  return { x: v.a.x, z: h.a.z };
}

/** All junctions of a segment list (pairwise crossings, merged by position). */
export function computeJunctions(segments: readonly RoadSegment[]): Junction[] {
  const byKey = new Map<string, { position: Vec2; segmentIds: Set<string> }>();
  for (let i = 0; i < segments.length; i++) {
    for (let j = i + 1; j < segments.length; j++) {
      const p = intersect(segments[i]!, segments[j]!);
      if (!p) continue;
      const key = `${Math.round(p.x)}:${Math.round(p.z)}`;
      const existing = byKey.get(key) ?? { position: p, segmentIds: new Set<string>() };
      existing.segmentIds.add(segments[i]!.id);
      existing.segmentIds.add(segments[j]!.id);
      byKey.set(key, existing);
    }
  }
  return [...byKey.entries()].map(([key, v]) => ({
    id: `junction-${key}`,
    position: v.position,
    segmentIds: [...v.segmentIds].sort(),
  }));
}

/**
 * Road graph for connectivity checks and vehicle routing: nodes are
 * junctions plus segment endpoints; edges are the stretches between
 * consecutive nodes along each segment.
 */
export interface RoadGraph {
  readonly nodes: readonly Vec2[];
  /** Pairs of node indices. */
  readonly edges: readonly (readonly [number, number])[];
}

export function buildRoadGraph(segments: readonly RoadSegment[]): RoadGraph {
  const junctions = computeJunctions(segments);
  const nodes: Vec2[] = [];
  const nodeKey = (p: Vec2): string => `${Math.round(p.x * 2) / 2}:${Math.round(p.z * 2) / 2}`;
  const indexByKey = new Map<string, number>();
  const nodeIndex = (p: Vec2): number => {
    const key = nodeKey(p);
    const existing = indexByKey.get(key);
    if (existing !== undefined) return existing;
    nodes.push(p);
    indexByKey.set(key, nodes.length - 1);
    return nodes.length - 1;
  };
  const edges: [number, number][] = [];
  for (const segment of segments) {
    const points: Vec2[] = [segment.a, segment.b];
    for (const junction of junctions) {
      if (junction.segmentIds.includes(segment.id)) points.push(junction.position);
    }
    const horizontal = isHorizontal(segment);
    points.sort((p, q) => (horizontal ? p.x - q.x : p.z - q.z));
    for (let i = 0; i + 1 < points.length; i++) {
      const a = nodeIndex(points[i]!);
      const b = nodeIndex(points[i + 1]!);
      if (a !== b) edges.push([a, b]);
    }
  }
  return { nodes, edges };
}

/** Indices of nodes reachable from `start` in the graph. */
export function reachableNodes(graph: RoadGraph, start: number): Set<number> {
  const adjacency = new Map<number, number[]>();
  for (const [a, b] of graph.edges) {
    adjacency.set(a, [...(adjacency.get(a) ?? []), b]);
    adjacency.set(b, [...(adjacency.get(b) ?? []), a]);
  }
  const seen = new Set<number>([start]);
  const queue = [start];
  while (queue.length > 0) {
    const node = queue.pop()!;
    for (const next of adjacency.get(node) ?? []) {
      if (!seen.has(next)) {
        seen.add(next);
        queue.push(next);
      }
    }
  }
  return seen;
}

/** Nearest graph node index to a point. */
export function nearestNode(graph: RoadGraph, point: Vec2): number {
  let best = 0;
  let bestDistance = Infinity;
  graph.nodes.forEach((node, i) => {
    const d = Math.hypot(node.x - point.x, node.z - point.z);
    if (d < bestDistance) {
      bestDistance = d;
      best = i;
    }
  });
  return best;
}

/**
 * Sample points along a segment's right-hand driving lane in the direction
 * a-to-b (`forward`) or b-to-a. Vehicles use these as waypoints.
 */
export function lanePath(segment: RoadSegment, forward: boolean, spacing = 8): Vec2[] {
  const from = forward ? segment.a : segment.b;
  const to = forward ? segment.b : segment.a;
  const dx = to.x - from.x;
  const dz = to.z - from.z;
  const length = Math.hypot(dx, dz);
  if (length < 1e-6) return [from];
  const ux = dx / length;
  const uz = dz / length;
  // Right-hand offset: perpendicular (uz, -ux) points to the driver's right.
  const laneOffset = segment.width / 4 + segment.median / 2;
  const ox = uz * laneOffset;
  const oz = -ux * laneOffset;
  const count = Math.max(2, Math.ceil(length / spacing) + 1);
  const points: Vec2[] = [];
  for (let i = 0; i < count; i++) {
    const t = i / (count - 1);
    points.push({ x: from.x + dx * t + ox, z: from.z + dz * t + oz });
  }
  return points;
}

/** Street lamp positions along a segment, both sides, at fixed spacing. */
export function lampPositions(segment: RoadSegment, spacing = 26): Vec2[] {
  const dx = segment.b.x - segment.a.x;
  const dz = segment.b.z - segment.a.z;
  const length = Math.hypot(dx, dz);
  if (length < spacing) return [];
  const ux = dx / length;
  const uz = dz / length;
  const offset = segment.width / 2 + segment.median / 2 + segment.sidewalk * 0.55;
  const lamps: Vec2[] = [];
  const count = Math.floor(length / spacing);
  for (let i = 1; i <= count; i++) {
    const t = (i - 0.5) * spacing;
    const px = segment.a.x + ux * t;
    const pz = segment.a.z + uz * t;
    // Alternate sides for avenues; both sides for the boulevard.
    if (segment.roadClass === 'boulevard' || i % 2 === 0) {
      lamps.push({ x: px + uz * offset, z: pz - ux * offset });
    }
    if (segment.roadClass === 'boulevard' || i % 2 === 1) {
      lamps.push({ x: px - uz * offset, z: pz + ux * offset });
    }
  }
  return lamps;
}
