"""Ideal and noisy Aer executions plus exact statevectors.

All sampled results are produced with explicit seeds so committed sample
traces can be regenerated byte-identically.
"""

from __future__ import annotations

from qiskit import QuantumCircuit
from qiskit.quantum_info import Statevector
from qiskit_aer import AerSimulator
from qiskit_aer.noise import (
    NoiseModel,
    ReadoutError,
    amplitude_damping_error,
    depolarizing_error,
    phase_damping_error,
)


def exact_statevector(qc: QuantumCircuit) -> list[list[float]]:
    """Statevector of a measurement-free circuit as [re, im] pairs."""
    sv = Statevector(qc)
    return [[float(a.real), float(a.imag)] for a in sv.data]


def normalize_counts_keys(counts: dict[str, int]) -> dict[str, int]:
    """Strips the spaces Qiskit inserts between classical registers."""
    return {k.replace(" ", ""): int(v) for k, v in counts.items()}


def run_ideal(qc: QuantumCircuit, shots: int, seed: int) -> dict[str, int]:
    # max_parallel_threads=1: Aer's shot-level parallelism partitions the RNG
    # stream by thread count, which varies with machine load and breaks
    # byte-identical regeneration of committed traces. The circuit is run
    # without a transpile step for the same reason: re-transpilation was
    # observed to produce equal-but-differently-sampled circuits, and every
    # gate the bridge emits is natively supported by Aer.
    sim = AerSimulator(seed_simulator=seed, max_parallel_threads=1)
    result = sim.run(qc, shots=shots).result()
    return normalize_counts_keys(result.get_counts())


def build_noise_model(
    readout_error: float = 0.0,
    depolarizing_1q: float = 0.0,
    depolarizing_2q: float = 0.0,
    amplitude_damping: float = 0.0,
    phase_damping: float = 0.0,
) -> NoiseModel:
    """Builds an Aer noise model mirroring the browser-simulator channels."""
    model = NoiseModel()
    one_qubit_error = None
    if depolarizing_1q > 0:
        one_qubit_error = depolarizing_error(depolarizing_1q, 1)
    if amplitude_damping > 0:
        ad = amplitude_damping_error(amplitude_damping)
        one_qubit_error = ad if one_qubit_error is None else one_qubit_error.compose(ad)
    if phase_damping > 0:
        pd = phase_damping_error(phase_damping)
        one_qubit_error = pd if one_qubit_error is None else one_qubit_error.compose(pd)
    if one_qubit_error is not None:
        model.add_all_qubit_quantum_error(one_qubit_error, ["rz", "sx", "x", "h", "u", "u3", "id"])
    if depolarizing_2q > 0:
        model.add_all_qubit_quantum_error(depolarizing_error(depolarizing_2q, 2), ["cx", "cz"])
    if readout_error > 0:
        model.add_all_qubit_readout_error(
            ReadoutError([[1 - readout_error, readout_error], [readout_error, 1 - readout_error]])
        )
    return model


def run_noisy(
    qc: QuantumCircuit,
    shots: int,
    seed: int,
    noise_model: NoiseModel,
) -> dict[str, int]:
    sim = AerSimulator(seed_simulator=seed, noise_model=noise_model, max_parallel_threads=1)
    result = sim.run(qc, shots=shots).result()
    return normalize_counts_keys(result.get_counts())
